name: Compilar APK de Android

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el proyecto
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Configurar Gradle en la máquina virtual
      uses: gradle/actions/setup-gradle@v3

    - name: Regenerar ejecutable gradlew
      run: gradle wrapper

    - name: Dar permisos de ejecución a Gradle
      run: chmod +x gradlew

    # Generar el Keystore de firmas que exige el proyecto
    - name: Generar Keystore de depuración (debug.keystore)
      run: |
        keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

    # Generar google-services.json usando el nombre real de paquete de tu App
    - name: Generar google-services.json de prueba
      run: |
        echo '{"project_info":{"project_number":"123456789","project_id":"dummy-id"},"client":[{"client_info":{"mobilesdk_app_id":"1:123456789:android:123456","android_client_info":{"package_name":"com.utk.noted.ia"}},"api_key":[{"current_key":"dummy_key"}]}]}' > app/google-services.json

    - name: Compilar APK de depuración (Debug)
      run: ./gradlew assembleDebug

    - name: Subir el archivo APK resultante
      uses: actions/upload-artifact@v4
      with:
        name: UTKNotes_IA
        path: app/build/outputs/apk/debug/UTKNotes.apk
